# Generated by Django 6.0.3 on 2026-03-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail_file_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
